site_name: My Docs

site_url: https://srucreative-br.github.io/worksamples/

nav:
  - Work samples: docs/README.md
  - About: docs/about.md

theme:
  name: material

  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
